server:
  port: 8081 # Port riêng cho service này

spring:
  application:
    name: USER-SERVICE # Tên sẽ đăng ký với Eureka

  # Cấu hình kết nối đến database pg_user (từ docker-compose)
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb?sessionTimezone=Asia/Ho_Chi_Minh
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Tự động cập nhật schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    show-sql: true # Hiển thị câu lệnh SQL trong log (tốt cho debug)

# Cấu hình để đăng ký với Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
